// src/components/FavoritePreview.svelte
<script>
	import { fragment, graphql } from '$houdini'

	let { species } = $props()

	const data = fragment(species, graphql(`
		fragment FavoritePreview on Species {
			id
			name
			sprites {
				front
			}
		}
	`))
</script>

<a href="/{$data.id}">
	<img src={$data.sprites.front} alt="{$data.name} sprite" />
</a>

<style>
	a {
		display: flex;
		flex-direction: column;
	}
</style>

// src/components/FavoritePreview.tsx
import { useFragment, graphql } from '$houdini'
import type { FavoritePreview as FavoritePreviewFragment } from '$houdini'

export function FavoritePreview({ species }: { species: FavoritePreviewFragment }) {
	const data = useFragment(
		species,
		graphql(`
			fragment FavoritePreview on Species {
				id
				name
				sprites {
					front
				}
			}
		`)
	)

	return (
		<a href={`/${data.id}`} className="flex flex-col no-underline">
			<img src={data.sprites.front} alt={`${data.name} sprite`} />
		</a>
	)
}
