// src/components/FavoritesContainer.tsx
import type { ReactNode } from 'react'

export function FavoritesContainer({ children }: { children: ReactNode }) {
	return (
		<div
			id="favorites-container"
			className="absolute left-0 right-0 top-0 flex flex-col border-[10px] border-double border-black bg-white rounded-[15px] h-[130px]"
		>
			<h2 className="p-0 m-0 ml-[10px] mt-[3px] text-2xl"
				style={{ fontFamily: "'VT323'" }}>
				Favorites
			</h2>
			<div className="flex flex-row overflow-x-auto overflow-y-hidden h-full">{children}</div>
		</div>
	)
}

// src/components/FavoritesContainer.svelte
<script>
	let { children } = $props()
</script>

<div id="favorites-container">
	<h2>Favorites</h2>
	<div>
		{@render children?.()}
	</div>
</div>

<style>
	h2 {
		padding: 0;
		margin: 0;
		margin-left: 10px;
		margin-top: 3px;
	}

	#favorites-container {
		position: absolute;
		left: 0;
		right: 0;
		top: 0;
		display: flex;
		flex-direction: column;
		border: 10px double black;
		background: white;
		border-radius: 15px;
		height: 130px;
	}

	#favorites-container div {
		display: flex;
		flex-direction: row;
		overflow-x: auto;
		overflow-y: hidden;
		height: 100%;
	}

	:global(#favorites-container ~ #pokedex) {
		margin-top: 200px;
	}

	:global(#favorites-container p) {
		padding: 0;
		margin: 0;
		margin-top: -10px;
		margin-left: 10px;
		display: flex;
		flex-grow: 1;
		flex-direction: row;
		align-items: center;
	}

	:global(#favorites-container p),
	h2 {
		font-size: 24px;
		font-family: 'VT323';
	}
</style>
