// src/components/SpeciesPreviewPlaceholder.svelte
<script>
    import { Display } from '.'
    import Number from './SpeciesPreviewNumber.svelte'

    export let number
</script>

<div class="">
    <Number value={number}/>
    <div class="sprite placeholder-background">
        <div class="poke-ball">
            <div class="poke-ball-top" />
            <div class="poke-ball-center" />
            <div class="poke-ball-bottom" />
        </div>
    </div>
    <Display>No Data</Display>
</div>

<style>
    .placeholder-background { 
        background: linear-gradient(15deg, #83887b 64%, #8b8f81 70%, #8b8f81 81%, #babfb1 86%, #8b8f81 89%, #8b8f81 100%);
        display: flex;
        justify-content: center;
        align-items: center;
        width: 102px;
        height: 102px;
    }

    .poke-ball { 
        border: solid black 4px;
        background: black;
        border-radius: 50%;
        height: 50px;
        width: 50px;
        display: flex;
        flex-direction: column;
        overflow: hidden;
        align-items: center;
        position: relative;
        opacity: 0.8;
    }

    .poke-ball-top { 
        background: #83887a;
        flex: 1;
        width: 100%;
        opacity: 0.3;
    }

    .poke-ball-center { 
        display: flex;
        width: 22px;
        height: 22px;
        border: solid black 4px;
        border-radius: 50%;
        align-items: center;
        justify-content: center;
        position: absolute;
        top: 10px;
    }

    .poke-ball-bottom { 
        background: #83887a;
        flex: 1;
        width: 100%;
    }
</style>

// src/components/SpeciesPreviewPlaceholder.tsx
import { Display } from "./Display";
import { SpeciesPreviewNumber } from "./SpeciesPreviewNumber";
import { Shimmer } from "./Shimmer";

export function SpeciesPreviewPlaceholder({
	number,
	loading,
}: {
	number: number;
	loading?: boolean;
}) {
	return (
		<div>
			<SpeciesPreviewNumber value={number} />
			<div
				className="flex justify-center items-center h-[102px] w-[102px] rounded-[5px] my-[10px] box-border"
				style={{
					imageRendering: "pixelated",
					border: "inset #9aa28b 3px",
					background:
						"linear-gradient(15deg, #83887b 64%, #8b8f81 70%, #8b8f81 81%, #babfb1 86%, #8b8f81 89%, #8b8f81 100%)",
				}}
			>
				<div className="border-[4px] border-solid border-black bg-black rounded-full h-[50px] w-[50px] flex flex-col overflow-hidden items-center relative opacity-80">
					<div className="bg-[#83887a] flex-1 w-full opacity-30" />
					<div className="flex w-[22px] h-[22px] border-[4px] border-solid border-black rounded-full items-center justify-center absolute top-[10px]" />
					<div className="bg-[#83887a] flex-1 w-full" />
				</div>
			</div>
			<Display>
				{loading ? <Shimmer width="70px" height="1em" /> : "No Data"}
			</Display>
		</div>
	);
}
