// src/components/SpeciesPreviewNumber.tsx
export function SpeciesPreviewNumber({ value }: { value: number }) {
	const Is = Array.from({ length: value })
		.map(() => 'I')
		.join('')

	return (
		<div
			className="text-center text-[1.25em] tracking-[2px] bg-transparent border-none text-black"
			style={{ fontFamily: "'Staatliches', cursive", textShadow: '-1px 1px #e78181' }}
		>
			{Is}
		</div>
	)
}

// src/components/SpeciesPreviewNumber.svelte
<script>
    export let value
    const Is = Array.from({length: value}).map(() => 'I').join('')
</script>

<div>
    {Is}
</div>

<style>
    div { 
        text-align: center;
        font-family: "Staatliches", cursive;
        font-size: 1.25em;
        letter-spacing: 2px;
        background: transparent;
        border: none;
        text-shadow: #e78181 -1px 1px;
        color: black;
    }
</style>
