// src/components/SpeciesPreview.svelte
<script>
    import { graphql, fragment } from '$houdini'
    import { Sprite, Display } from '.'
    import Number from './SpeciesPreviewNumber.svelte'

    export let species
    export let number

    const data = fragment(graphql`
        fragment SpeciesPreview on Species { 
            name
            id
			sprites { 
				front
			}
        }
    `, species)
</script>

<a href={$data.id}>
    <Number value={number} />
    <Sprite 
        src={$data.sprites.front}
        speciesName={$data.name} 
        class="preview-sprite" 
    />
    <Display>
        {$data.name}
    </Display>
</a>

<style>
    :global(.preview-sprite) {
        height: 102px;
        width: 102px;
    }
</style>

// src/components/SpeciesPreview.tsx
import { useFragment, graphql } from '$houdini'
import type { SpeciesPreview$key } from '$houdini'
import { Sprite } from './Sprite'
import { Display } from './Display'
import { SpeciesPreviewNumber } from './SpeciesPreviewNumber'

export function SpeciesPreview({
	species,
	number,
}: {
	species: SpeciesPreview$key
	number: number
}) {
	const data = useFragment(
		species,
		graphql(`
			fragment SpeciesPreview on Species {
				name
				id
				sprites {
					front
				}
			}
		`)
	)

	return (
		<a href={`/${data.id}`} className="no-underline">
			<SpeciesPreviewNumber value={number} />
			<Sprite
				src={data.sprites.front}
				speciesName={data.name}
				className="h-[102px] w-[102px]"
			/>
			<Display>{data.name}</Display>
		</a>
	)
}
